title: Hi,
author: Irine Stephanie
email: pinxhoes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the place where I learn, build projects, and show you the results.

# social links
twitter_username: WhereIsIrine # DO NOT include the @ character, or else the build will fail!
github_username:  pinxhoes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
